/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rryutxntfvqjtmvtozdh";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyeXV0eG50ZnZxanRtdnRvemRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzg3NTgsImV4cCI6MjA3Mjc1NDc1OH0.mlLpxdVdimpgkS7KeQSnFGq0hU8HIJXyhw_fWxMknnQ";
